[package]
name = "pdf"
version = "0.7.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian Köln <sebk@rynx.org>"]
repository = "https://github.com/pdf-rs"
readme = "README.md"
keywords = ["pdf"]
license = "MIT"
documentation = "https://docs.rs/pdf"
edition = "2018"
description = "PDF reader"

[features]
mmap = ["memmap"]
dump = ["tempfile"]

[dependencies.pdf_derive]
path = "../pdf_derive"

[dependencies.encoding]
git = "https://github.com/pdf-rs/encoding/"

[dependencies]
snafu = "0.4"
num-traits = "0.1.36"
inflate = "0.4.5"
byteorder = "1.0.0"
itertools = "0.6.0"
ordermap = "0.2.9"
memmap = { version = "0.7.0", optional = true }
lzw = "0.10.0"
tuple = { git = "https://github.com/s3bk/tuple" }
glob = "0.2.11"
chrono = "0.4.0"
once_cell = "0.2"
log = "0.4.8"
tempfile = { version = "3.1.0", optional = true }
md5 = "0.6"
png = "0.15"

[lib]
doctest = false

